import os
import json
from datetime import datetime
from pathlib import Path

class VirtualFileSystem:
    def __init__(self, data_dir="data"):
        self.data_dir = Path(data_dir)
        self.data_dir.mkdir(exist_ok=True)
    
    def write_report(self, filename: str, content: str):
        filepath = self.data_dir / filename
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        full_content = f"""---
Generated by Autonomous Cognitive Engine
Timestamp: {timestamp}
Filename: {filename}
---

{content}
"""
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(full_content)
        return f"Saved {filename} ({len(content)} chars)"
    
    def list_reports(self):
        return [f.name for f in self.data_dir.glob("*.txt")]

vfs = VirtualFileSystem()
